### ISSUE TITLE
Accessing UseServiceProviderFactory method

### ISSUE THREAD

**Issue by metkor** [GoogleCloudPlatform/functions-framework-dotnet#181] opened 2020-12-23 12:14 UTC
Hi,

Is it possible to call UseServiceProviderFactory somehow? In ordinary projects, We are doing it in Main function in Program.cs. But now it looks we don't have access to Program.cs.

**Comment by jskeet** [comment] 2020-12-23 12:29
That's not something I'm familiar with. I'll look into it when I'm back from vacation - so January 5th.

**Comment by metkor** [comment] 2020-12-23 13:02
Thanks a lot. I am using it for adding AutofacServiceProviderFactory.

**Comment by metkor** [comment] 2021-01-07 12:55
Thanks @jskeet I will try to find a workaround

**Comment by jskeet** [comment] 2021-01-21 09:50
@metkor: Okay, I've got a PR (#181) which would enable this, but I want to check it's actually going to be useful to you before we merge it.

In order to use this, you would have to disable the entry point in the project file, and write your own entry point. So like this:

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AutoGenerateEntryPoint>false</AutoGenerateEntryPoint>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="7.1.0" />
    <PackageReference Include="Google.Cloud.Functions.Hosting" Version="[whatever this is published in]" />
  </ItemGroup>
</Project>
```

And entry point:

```csharp
using Autofac.Extensions.DependencyInjection;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;
using System;
using System.Threading.Tasks;

namespace CustomServiceProviderTest
{
    public class Program
    {
        static async Task<int> Main(string[] args)
        {
            // Disables a log 
            Environment.SetEnvironmentVariable("ASPNETCORE_URLS", null);

            // Build the host using Autofac for DI, and configure the Functions Framework
            using var host = Host.CreateDefaultBuilder()
                .UseServiceProviderFactory(new AutofacServiceProviderFactory())
                .ConfigureWebHostDefaults(webHostBuilder => webHostBuilder.ConfigureFunctionsFramework(typeof(Program).Assembly, args))
                .Build();

            // Run the server
            await host.RunAsync();
            return 0;
        }
    }
}
```

I can confirm that much works, and we get an Autofac service provider... but I don't yet have a clear idea of what you'd do with it... it could be that we'd need to add hooks elsewhere to call `ConfigureContainer` etc.

Could you let me know what you need from the framework *beyond* the ability to call `UseServiceProviderFactory`?

(If you're happy to pull the code in the PR to test it, I can walk you through how to make that work locally if you'd like.)

**Comment by metkor** [comment] 2021-01-21 12:25
@jskeet thank you very much. I will check it in short time and will let you know about the result. 

In autofac [documentation](https://autofaccn.readthedocs.io/en/latest/integration/aspnetcore.html) it is told that: 

> Hosting changed in ASP.NET Core 3.0 and requires a different integration. You can no longer return IServiceProvider from ConfigureServices, nor can you add your service provider factory to the service collection.

> This` is for ASP.NET Core 3+ and the .NET Core 3+ generic hosting support:


Infact I need to intercept some of my calls in my application, not to log for my case but you can think like that. Autofac provides that. But builtin dependency injection mechanism in .net core not providing this functionality. So thats why I am trying to call UseServiceProviderFactory.

Thanks again.

**Comment by jskeet** [comment] 2021-01-21 12:48
Again, I'm still not sure what other code you'd need beyond `UseServiceProviderFactory` though. Are you able to provide a minimal example for what you'd *expect* to do here? I read that Autofac documentation, but it refers to things like `ConfigureContainer` in startup classes, which *wouldn't* be supported with just this PR.

If it's a matter of "I want to be able to get at an `IServiceProvider` in my function" then it probably won't be too hard to create an example doing that - ideally one we could then include in the documentation.

**Comment by metkor** [comment] 2021-01-22 12:30
@jskeet I will create a sample app. Is it ok as an ordinary web app or app for cloud function with the pr?

**Comment by jskeet** [comment] 2021-01-22 13:59
A Cloud Function app would be ideal, as it would show me what you'd expect to write, and I can try to get as close to that as possible. Please do feel free to add comments with "This method should be automatically called as part of startup" or whatever. Hope that makes sense!

**Comment by metkor** [comment] 2021-02-09 09:50
Hi @jskeet First, sorry for my late response.

I created a small project, how can share it with you? 
I write small comments in MethodLoggingAspect.cs file.

**Comment by jskeet** [comment] 2021-02-09 10:03
If you can share a repo on GitHub, or put it in a zip file (without the obj and bin directories) you could just attach it here.

**Comment by metkor** [comment] 2021-02-09 10:03
I attached it, thanks

**Comment by jskeet** [comment] 2021-02-09 10:05
Okay - I'll try to have a look later in the week, but it may be next week.

**Comment by metkor** [comment] 2021-02-09 10:07
Ok, thanks a lot @jskeet

**Comment by jskeet** [comment] 2021-02-10 10:59
Hmm. I've had a look, and I rapidly got lost I'm afraid. I've found the [StartupLoader](https://github.com/dotnet/aspnetcore/blob/main/src/Hosting/Hosting/src/Internal/StartupLoader.cs) which would be responsible for calling ConfigureContainer, but trying to work out exactly how that's called is beyond me right now.

I suspect this would be feasible with the help of the Autofac team, who I'm sure know the details of how all of this works intimately. Do you know any Autofac developers who might be interested in collaborating on this?

**Comment by jskeet** [comment] 2021-02-10 11:02
It's possible I can adapt https://github.com/junalmeida/autofac-azurefunctions/tree/master/Autofac.Extensions.DependencyInjection.AzureFunctions - or work with the author of that. I'll reach out and see if they're interested.

**Comment by metkor** [comment] 2021-02-10 12:37
In fact, I don't know know any Autofac developers. I will also try to reach someone to collaborate in autofac side. 

Thanks a lot.

**Comment by anthonyserverless** [comment] 2021-11-17 16:02
@jskeet is there any update on this? I'm running into the same issue. If it's not ready, @metkor did you end up finding a workaround?

**Comment by jskeet** [comment] 2021-11-17 16:09
@anthonyserverless: When you say "the same issue" - do you mean trying to use Autofac, or UseServiceProviderFactory in general?

Either way, no, we didn't end up supporting it for the first release - I did try for quite a while with Autofac, but it got rather gnarly. Other UseServiceProviderFactory use cases *might* be simpler.

**Comment by anthonyserverless** [comment] 2021-11-17 16:31
I'm trying to use Autofac

**Comment by jskeet** [comment] 2021-11-17 16:33
Right. I'm afraid that's not supported at the moment; I can't promise it ever will be, simply because of the complexities of doing so. Your desire for it is noted though.

**Comment by anthonyserverless** [comment] 2021-11-17 16:50
Ok. Thank you very much for your help

**Comment by jskeet** [comment] 2024-04-08 14:00
Closing this as I doubt that we'll end up ever revisiting this, or if we do it'll be for a different reason anyway.

**Closed by jskeet** 2024-04-08 14:00 UTC
Labels: enhancement

**Comment by oleksiik-opti** [comment] 2025-09-19 08:14
Hi. I'd like to elaborate on a use case when it is good-to-have customization:

There's a service developed with Autofac, which relies upon some of it's features which are not available in M.E.DI (e.g., OnActivating hooks, etc).

At some point, a part of this service is extracted into the cloud function - for performance reasons.

Currently it seems that the only viable approach is to duplicate the registration infra + workaround M.E.DI limitations. It is inconvenient as it takes more time and complicates the source code.
