### ISSUE TITLE
Work out what to do about communicating errors from functions to callers

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/functions-framework-dotnet#37] opened 2020-04-09 06:27 UTC
In particular, what do we do beyond status codes? Where do we put messages?
What happens if you've written something to the body already?

**Comment by josephlewis42** [comment] 2023-04-06 17:18
Hi @jskeet, I'm going to mark this as a duplicate of: https://github.com/GoogleCloudPlatform/functions-framework/issues/46. Once we figure out our ideal across languages I think what to do with FF dotnet will be clearer.

**Closed by josephlewis42** 2023-04-06 17:18 UTC
