### ISSUE TITLE
Private NuGet Feeds

### ISSUE THREAD

**Issue by JoelW16** [GoogleCloudPlatform/functions-framework-dotnet#236] opened 2022-01-17 10:26 UTC
Hey there,

I am trying to deploy a function that uses a library from a private NuGet feed. I have deployed the cloud function with a NuGet.Config file at the solution, project level, and everywhere mentioned [here (Common NuGet configurations)](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#config-file-locations-and-uses).
The deployment fails each time, with the logs showing it always attempting to pull the library from nuget.org. Are custom NuGet feeds supported?

Thanks

**Comment by jskeet** [comment] 2022-01-17 10:42
Custom feeds would need to be supported in the [build pack](https://github.com/GoogleCloudPlatform/buildpacks/tree/main/builders/gcf/dotnet3). I don't know whether this (or the equivalent) is supported for any language at the moment.

Assigning to Matthew who can speak to this more and prioritize it appropriately. Sorry not to have a better answer for you at the moment.

**Comment by matthewrobertson** [comment] 2022-01-20 05:53
This does sounds like a bug in the Buildpacks. I would expect that including the NuGet.Config at the solution directory would work. One thing to check is that it was actually included with the source code uploaded to Cloud Build (i.e. it wasn't included in your [.gitignore or .gcloudignore](https://cloud.google.com/sdk/gcloud/reference/topic/gcloudignore)). 

@JoelW16 would you mind sharing a minimal sample that I could use reproduce the issue?

**Comment by josephlewis42** [comment] 2023-04-06 17:14
I'm going to close the issue here since it appears like this is mostly buildpack related. If you have examples, please refer them to https://github.com/GoogleCloudPlatform/buildpacks/issues/171.

Feel free to reach out if you need any other help!

**Closed by josephlewis42** 2023-04-06 17:14 UTC
Labels: enhancement
