### ISSUE TITLE
Getting error : A task was canceled 

### ISSUE THREAD

**Issue by yashhema** [GoogleCloudPlatform/functions-framework-dotnet#222] opened 2021-09-07 23:33 UTC
Hello,
I have deployed .net core as google cloud functions (http). After every 2 or 3rd call I get the error - A task was canceled.
I have increased timeout , nothing is printed on the server side. Any idea what i can do

**Comment by yashhema** [comment] 2021-09-07 23:35
The same function will work if i call it again (after getting the error)

**Comment by jskeet** [comment] 2021-09-08 05:42
Hmm... are you able to provide a function that reproduces the problem so that I can investigate further?

**Comment by yashhema** [comment] 2021-09-09 22:43
For me , u can take any cloud function , and call them in with same parameter multiple times in series.  something like
call funcA
call funcA
call FuncA

For me , every 3rd or 4th call gets the above error

**Comment by jskeet** [comment] 2021-09-10 06:27
So do you see this behavior with the "hello, world" function that you get out of the box with `dotnet new gcf-http` for example?
How are you calling the function? Do you see the same issue if you just refresh with the browser? (I've just tried that with a personal function, simply hitting refresh 10 times, and it was fine.)

**Comment by jskeet** [comment] 2021-09-29 07:37
Closing due to lack of information for now - please add another comment if you are still seeing a problem, answering the questions from September 10th.

**Closed by jskeet** 2021-09-29 07:37 UTC
